// Generated by gencpp from file visualization/PlanNodesRequest.msg
// DO NOT EDIT!


#ifndef VISUALIZATION_MESSAGE_PLANNODESREQUEST_H
#define VISUALIZATION_MESSAGE_PLANNODESREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace visualization
{
template <class ContainerAllocator>
struct PlanNodesRequest_
{
  typedef PlanNodesRequest_<ContainerAllocator> Type;

  PlanNodesRequest_()
    : nodes()
    , solution()  {
    }
  PlanNodesRequest_(const ContainerAllocator& _alloc)
    : nodes(_alloc)
    , solution(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _nodes_type;
  _nodes_type nodes;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _solution_type;
  _solution_type solution;




  typedef boost::shared_ptr< ::visualization::PlanNodesRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::visualization::PlanNodesRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PlanNodesRequest_

typedef ::visualization::PlanNodesRequest_<std::allocator<void> > PlanNodesRequest;

typedef boost::shared_ptr< ::visualization::PlanNodesRequest > PlanNodesRequestPtr;
typedef boost::shared_ptr< ::visualization::PlanNodesRequest const> PlanNodesRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::visualization::PlanNodesRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::visualization::PlanNodesRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace visualization

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::visualization::PlanNodesRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::visualization::PlanNodesRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::visualization::PlanNodesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::visualization::PlanNodesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::visualization::PlanNodesRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::visualization::PlanNodesRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::visualization::PlanNodesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7df653d1b1362ece68e40d75369740b5";
  }

  static const char* value(const ::visualization::PlanNodesRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7df653d1b1362eceULL;
  static const uint64_t static_value2 = 0x68e40d75369740b5ULL;
};

template<class ContainerAllocator>
struct DataType< ::visualization::PlanNodesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "visualization/PlanNodesRequest";
  }

  static const char* value(const ::visualization::PlanNodesRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::visualization::PlanNodesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string nodes\n\
string solution\n\
";
  }

  static const char* value(const ::visualization::PlanNodesRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::visualization::PlanNodesRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.nodes);
      stream.next(m.solution);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct PlanNodesRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::visualization::PlanNodesRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::visualization::PlanNodesRequest_<ContainerAllocator>& v)
  {
    s << indent << "nodes: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.nodes);
    s << indent << "solution: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.solution);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VISUALIZATION_MESSAGE_PLANNODESREQUEST_H
